GET http://localhost:3000/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiSnVhbmFuIiwiY3JlYXRlZEF0IjoxNTg5ODI2MzE4LCJleHBpcmVkQXQiOjE1ODk4MjY2MTh9.CajCpzzGGkwpAVXW7YqOU7amDPFwL9EAnGPSoTcuDyM

###
POST http://localhost:3000/api/proyectos
Content-Type: application/json

{
    "titulo": "Proyecto",
    "descripcion": "Esta es la descripción",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quien-somos"
}

###
PUT http://localhost:3000/api/proyectos/5eb99e7fd9a6130d7b5c9d8e
Content-Type: application/json

{
    "titulo": "Proyecto EDITADO V2",
    "descripcion": "Esta es la descripción",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quien-somos"
}

###
DELETE http://localhost:3000/api/proyectos/5eb99e6bd9a6130d7b5c9d8d

###
GET http://localhost:3000/api/token